### ISSUE TITLE
Error while running gaps.py

### ISSUE THREAD

**Issue by jkuser007** [baboons/samba4-gaps#17]
python3 gaps.py start
Traceback (most recent call last):
  File "/etc/gaps/gaps.py", line 35, in <module>
    daemon_runner = runner.DaemonRunner(app)
  File "/usr/lib/python3/dist-packages/daemon/runner.py", line 114, in __init__
    self._open_streams_from_app_stream_paths(app)
  File "/usr/lib/python3/dist-packages/daemon/runner.py", line 134, in _open_streams_from_app_stream_paths
    self.daemon_context.stderr = open(
ValueError: can't have unbuffered text I/O

**Comment by webbrain-one** [comment]
Thanks for reporting this! I've opened [PR #18](https://github.com/baboons/samba4-gaps/pull/18) to fix the `ValueError: can't have unbuffered text I/O` error you're seeing when running `gaps.py`. Let me know if you have any questions or run into any other issues!
